AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yerttle-create-aws

  SAM Template for Yerttle Tours audio transcription service

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.10
    Environment:
      Variables:
        BUCKET_NAME: yerttle_tours
        LANGUAGE_CODE: en-US
        TRANSCRIPTION_PREFIX: transcriptions/
        SENTIMENT_PREFIX: sentiment/

Resources:
  # Lambda function to start transcription when audio file is uploaded
  StartTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yerttle-start-transcription
      CodeUri: src/start_transcription/
      Handler: app.lambda_handler
      Description: Starts AWS Transcribe job when m4a file is uploaded to S3
      Policies:
        - S3ReadPolicy:
            BucketName: yerttle_tours
        - Statement:
          - Effect: Allow
            Action:
              - transcribe:StartTranscriptionJob
              - transcribe:GetTranscriptionJob
            Resource: '*'
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        S3AudioUpload:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - yerttle_tours
                object:
                  key:
                    - suffix: .m4a

  # Lambda function to process completed transcription
  ProcessTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yerttle-process-transcription
      CodeUri: src/process_transcription/
      Handler: app.lambda_handler
      Description: Processes completed transcription and saves results to S3
      Policies:
        - S3CrudPolicy:
            BucketName: yerttle_tours
        - Statement:
          - Effect: Allow
            Action:
              - transcribe:GetTranscriptionJob
            Resource: '*'
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        TranscribeComplete:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.transcribe
              detail-type:
                - Transcribe Job State Change
              detail:
                TranscriptionJobStatus:
                  - COMPLETED

  # IAM Role for Comprehend to access S3 (for async jobs)
  ComprehendServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: yerttle-comprehend-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: comprehend.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ComprehendS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::yerttle_tours
                  - arn:aws:s3:::yerttle_tours/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - arn:aws:s3:::yerttle_tours/sentiment/*
                  - arn:aws:s3:::yerttle_tours/comprehend-output/*

  # Lambda function to analyze sentiment, entities, and key phrases
  SentimentAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yerttle-sentiment-analysis
      CodeUri: src/sentiment_analysis/
      Handler: app.lambda_handler
      Description: Analyzes transcription using AWS Comprehend (sentiment, entities, key phrases)
      Timeout: 900
      Environment:
        Variables:
          COMPREHEND_ROLE_ARN: !GetAtt ComprehendServiceRole.Arn
      Policies:
        - S3CrudPolicy:
            BucketName: yerttle_tours
        - Statement:
          - Effect: Allow
            Action:
              - comprehend:DetectSentiment
              - comprehend:DetectEntities
              - comprehend:DetectKeyPhrases
              - comprehend:DetectDominantLanguage
              - comprehend:StartSentimentDetectionJob
              - comprehend:StartEntitiesDetectionJob
              - comprehend:StartKeyPhrasesDetectionJob
            Resource: '*'
        - Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt ComprehendServiceRole.Arn
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        TranscriptionJsonCreated:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - Object Created
              detail:
                bucket:
                  name:
                    - yerttle_tours
                object:
                  key:
                    - prefix: transcriptions/
                    - suffix: .json

  # Lambda function to process completed async Comprehend jobs
  ComprehendJobCompletionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: yerttle-comprehend-job-completion
      CodeUri: src/comprehend_job_completion/
      Handler: app.lambda_handler
      Description: Processes completed async Comprehend jobs and saves results to S3
      Policies:
        - S3CrudPolicy:
            BucketName: yerttle_tours
        - Statement:
          - Effect: Allow
            Action:
              - comprehend:DescribeSentimentDetectionJob
              - comprehend:DescribeEntitiesDetectionJob
              - comprehend:DescribeKeyPhrasesDetectionJob
            Resource: '*'
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Events:
        ComprehendSentimentComplete:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.comprehend
              detail-type:
                - Comprehend Sentiment Detection Job State Change
              detail:
                JobStatus:
                  - COMPLETED
        ComprehendEntitiesComplete:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.comprehend
              detail-type:
                - Comprehend Entities Detection Job State Change
              detail:
                JobStatus:
                  - COMPLETED
        ComprehendKeyPhrasesComplete:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.comprehend
              detail-type:
                - Comprehend Key Phrases Detection Job State Change
              detail:
                JobStatus:
                  - COMPLETED
